### ISSUE TITLE
Local variable 'fanart' referenced before assignment

### ISSUE THREAD

**Issue by fredrike** [custom-components/sensor.plex_recently_added#10]
The following entry in `configuration.yaml`

```yaml
  - platform: plex_recently_added
    token: !secret plex_token
    host: 192.168.1.2
    port: 32400
    download_images: true
    max: 5
```

Yields this error:  
```
plex_recently_added: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/plex_recently_added.py", line 262, in update
    if image_url(self.url_elements, True, fanart):
UnboundLocalError: local variable 'fanart' referenced before assignment
```

Using 0.2.0.

**Comment by fredrike** [comment]
Turns out my media type is **photo**.

It would make sense to only consider sections that are of type Movie or Series.

**Comment by maykar** [comment]
Hey sorry missed this email, but turns out you don't need my help.
Assuming, of course, you're the same Fredrick E that fixed it in a PR :) .
Thanks for that, really appreciate it!

**Comment by maykar** [comment]
Thanks for this, BTW. Appreciate it!
