### ISSUE TITLE
plex_recently_added: Error on device update!

### ISSUE THREAD

**Issue by gbdavidx** [custom-components/sensor.plex_recently_added#24]
Sensor not being created - was working fine, this is on the very latest version of home-assistant, .96.3

Tried clearing cache and reinstalling add-on no go

```
Log Details (ERROR)
Sat Jul 20 2019 14:05:56 GMT-0700 (Pacific Daylight Time)
plex_recently_added: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f362c668850>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.248,172.30.32.1', port=32400): Max retries exceeded with url: /photo/:/transcode?width=200&height=200&minSize=1&url=http%3A%2F%2F192.168.1.248%2C172.30.32.1%3A32400%2Flibrary%2Fmetadata%2F2815%2Fart%2F1563356803%3FX-Plex-Token%3Dx9c46MUfvvCmcgTHmbKM&X-Plex-Token=x9c46MUfvvCmcgTHmbKM (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f362c668850>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plex_recently_added/sensor.py", line 270, in update
    if image_url(self.url_elements, True, fanart):
  File "/config/custom_components/plex_recently_added/sensor.py", line 313, in image_url
    r = requests.head(url, verify=False)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.248,172.30.32.1', port=32400): Max retries exceeded with url: /photo/:/transcode?width=200&height=200&minSize=1&url=http%3A%2F%2F192.168.1.248%2C172.30.32.1%3A32400%2Flibrary%2Fmetadata%2F2815%2Fart%2F1563356803%3FX-Plex-Token%3Dx9c46MUfvvCmcgTHmbKM&X-Plex-Token=x9c46MUfvvCmcgTHmbKM (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f362c668850>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```

**Comment by gbdavidx** [comment]
i got it working by trying the ip address and not the host name

**Comment by maykar** [comment]
It seems that the plex api was changed recently and returns 2 IP addresses. The server_name "feature" has caused a bit of confusion anyhow so rather than fix I'm just going to remove. It added very little.
